# Generated by Django 4.2.5 on 2023-09-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(error_messages={'Please enter a Name'}, help_text='First Name', max_length=100)),
                ('last_name', models.CharField(error_messages={'Please enter a Name'}, help_text='Last Name', max_length=100)),
                ('message', models.TextField(error_messages={'required': 'This Field is required.'}, help_text='Please describe your matter.', max_length=1400)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
