# Generated by Django 4.2.5 on 2023-09-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact.jsx',
            name='email',
            field=models.EmailField(blank=True, help_text='(not required but needed if you expect a answer)', max_length=100, verbose_name='Your E-Mail Address'),
        ),
        migrations.AddField(
            model_name='contact.jsx',
            name='options',
            field=models.CharField(choices=[('security', 'Security'), ('problem', 'Problem'), ('questions', 'Questions'), ('praise/criticism', 'Praise/Criticism'), ('other', 'Other')], default='questions', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact.jsx',
            name='first_name',
            field=models.CharField(help_text='First Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact.jsx',
            name='last_name',
            field=models.CharField(help_text='Last Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact.jsx',
            name='message',
            field=models.TextField(help_text='Please describe your matter.', max_length=1400),
        ),
    ]
